apiVersion: v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    name: dpy-nextcloud
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name:  my-name
        image: nextcloud
