apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pv

spec:
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      labels:
        type: db
    spec:
      containers:
        - image: postgres:9.6.1
          name: postgres
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: dbdata
              mountPath: /var/lib/postgresql/data
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: dbdata
          persistentVolumeClaim:
              claimName: gluster-claim
